apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: moj-observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        isDefault: true
        jsonData:
          tlsSkipVerify: true
          httpMethod: POST
          timeInterval: 30s
          httpHeaderName1: Authorization
        secureJsonData:
          httpHeaderValue1: PLACEHOLDER_TOKEN
        editable: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-tempo-moj.moj-observability.svc.cluster.local:3200
        editable: true
        jsonData:
          tracesToMetrics:
            datasourceUid: prometheus
          tracesToLogs:
            datasourceUid: loki
          nodeGraph:
            enabled: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application
        editable: true
        jsonData:
          tlsSkipVerify: true
          httpHeaderName1: Authorization
        secureJsonData:
          httpHeaderValue1: PLACEHOLDER_TOKEN
