apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo-moj
  namespace: moj-observability
spec:
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-34-204.us-east-2.compute.internal
  storage:
    traces:
      backend: pv
      size: 50Gi
  jaegerui:
    enabled: true
    route:
      enabled: true
  multitenancy:
    enabled: false
  observability:
    metrics:
      serviceMonitors:
        enabled: true
